@startuml Montres_ecommerce
left to right direction
actor Client
actor Administrateur

rectangle "Montres_ecommerce" {
  usecase "Parcourir les montres" as UC_Browse
  usecase "Rechercher des montres" as UC_Search
  usecase "Ajouter au panier" as UC_AddCart
  usecase "Voir le panier" as UC_ViewCart
  usecase "Passer à la caisse" as UC_Checkout
  usecase "Passer commande" as UC_Order
  usecase "Laisser un avis" as UC_Review
  usecase "Gérer les produits" as UC_ManageProducts
  usecase "Gérer les commandes" as UC_ManageOrders
  usecase "Gérer les utilisateurs" as UC_ManageUsers
}

Client -- UC_Browse
Client -- UC_Search
Client -- UC_AddCart
Client -- UC_ViewCart
Client -- UC_Checkout
Client -- UC_Order
Client -- UC_Review

Administrateur -- UC_ManageProducts
Administrateur -- UC_ManageOrders
Administrateur -- UC_ManageUsers
@enduml
